pub mod auth;
pub mod users;
pub mod resources;
pub mod courses;
pub mod rooms;
pub mod time_slots;
pub mod timetable_entries;
pub mod substitutions;
pub mod availability;
pub mod conflicts;
pub mod draft_timetables;
pub mod published_timetables;
pub mod draft_entries;

pub use users::UserRepository;
pub use resources::ResourceRepository;
pub use courses::CourseRepository;
pub use rooms::RoomRepository;
pub use time_slots::TimeSlotRepository;
pub use timetable_entries::TimetableEntryRepository;
pub use substitutions::SubstitutionRepository;
pub use auth::AuthRepository;
pub use availability::Repository as AvailabilityRepository;
pub use conflicts::Repository as ConflictRepository;
pub use draft_timetables::Repository as DraftTimetableRepository;
pub use published_timetables::Repository as PublishedTimetableRepository;
pub use draft_entries::Repository as DraftEntryRepository;
